import type { Metadata } from 'next';
import { Roboto, Roboto_Mono } from 'next/font/google';
import './global.css';

const geistSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
});

const geistMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
